apiVersion: v1
kind: Secret
metadata:
  name: {{ include "homelab.fullname" . }}-credentials
  labels:
    {{- include "homelab.labels" . | nindent 4 }}
type: Opaque
stringData:
  mariadb-root-password: {{ required "secrets.mariadbRootPassword is required" .Values.secrets.mariadbRootPassword | quote }}
  mariadb-password: {{ required "secrets.wordpressDatabasePassword is required" .Values.secrets.wordpressDatabasePassword | quote }}
  redis-password: {{ required "secrets.redisPassword is required" .Values.secrets.redisPassword | quote }}

